# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 22:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Test_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtensionOnetoOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(default=b'NIST', max_length=20, verbose_name=b'Agency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
