# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_App', '0003_projectgroups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectG3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='projectgroups',
            name='name',
            field=models.CharField(default=b'', max_length=20, verbose_name=b'Group Name'),
        ),
    ]
