# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_App', '0007_auto_20160207_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to=b'files/%Y/%m/%d'),
        ),
    ]
