# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_App', '0008_auto_20160207_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'files/%Y/%m/%d')),
            ],
        ),
    ]
