# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 02:46
from __future__ import unicode_literals

import Test_App.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Test_App', '0012_auto_20160207_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCanvas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Test_App.models.user_directory_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
