# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 04:27
from __future__ import unicode_literals

import Test_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_App', '0013_uploadcanvas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcanvas',
            name='file',
            field=models.ImageField(upload_to=Test_App.models.user_directory_path),
        ),
    ]
