# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 20:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_App', '0016_auto_20160216_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectwall',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
